service: hello
#app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-3  
  apiGateway:
    shouldStartNameWithService: true

plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.hello

  hellouser:
    handler: handler.hellouser
    events:
      - http:
          method: GET
          path: /user

  hellouserparam:
    handler: handler.hellouserparam
    events:
      - http:
          method: GET
          path: /user/{name}

  createuser:
    handler: handler.createuser
    events:
      - http:
          method: POST
          path: /createuser
